### ISSUE TITLE
Property Search Result Listing Block

### ISSUE THREAD

**Issue by bstopp** [hlxsites/hsf-commonmoves#10]
More info needed on this - may be a full headless integration.

<img width="635" alt="Property_Search_Results_Commonwealth_Real_Estate___Berkshire_Hathaway_HomeServices" src="https://user-images.githubusercontent.com/6520270/224404629-c9602acb-307b-45f1-92b9-785527047457.png">

[Example Link](https://www.commonmoves.com/search?SearchType=Map&PropertyType=1%2C2&ApplicationType=FOR_SALE&ListingStatus=1&NewListing=false&Sort=PRICE_DESCENDING&PageSize=32&Page=1&NorthEastLatitude=42.928308834863444&NorthEastLongitude=-68.11380499917098&SouthWestLatitude=41.017246455973805&SouthWestLongitude=-71.79422492104598&SearchParameter=%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-71.79422492104598%2C42.928308834863444%5D%2C%5B-71.79422492104598%2C41.017246455973805%5D%2C%5B-68.11380499917098%2C41.017246455973805%5D%2C%5B-68.11380499917098%2C42.928308834863444%5D%2C%5B-71.79422492104598%2C42.928308834863444%5D%5D%5D%7D%7D%5D%7D&MapSearchType=MapBounds&isAgentPage=false&isFranchisePage=true&franchiseeCode=MA312)

**Comment by irenelagno** [comment]
Fixed with https://github.com/hlxsites/hsf-commonmoves/pull/88
