### ISSUE TITLE
Community Detail "Explore" selection

### ISSUE THREAD

**Issue by bstopp** [hlxsites/hsf-commonmoves#150]
Community detail pages have an option to "explore" more 

Hard coded or based on a point? (Seems to be hard coded).
<img width="239" alt="Explore_Acton__MA_with_Commonwealth_Real_Estate_Berkshire_Hathaway_HomeServices_network_agents__Market_Trends__Homes_for_Sale__and_more____Commonwealth_Real_Estate_Berkshire_Hathaway_HomeServices" src="https://github.com/hlxsites/hsf-commonmoves/assets/6520270/fb30c840-ef2a-4e0f-9c94-3448a5369ff6">

**Comment by rrusher** [comment]
https://www.commonmoves.com/communities/winthrop

<img width="1561" alt="Screenshot 2023-12-11 at 11 25 07 AM" src="https://github.com/hlxsites/hsf-commonmoves/assets/6796243/7be9d8cb-ffa0-4899-8211-d58bfcf6d238">
