### ISSUE TITLE
Account Profile detail block

### ISSUE THREAD

**Issue by bstopp** [hlxsites/hsf-commonmoves#151]
Logged-in state for Account profile page.

**Comment by badvision** [comment]
Two things stand out in the PUT request:
1) There is not a 1:1 correspondence with the profile values returned from the service.  There are some things in the profile that are not submitted back or have entirely different names.
2) Even for values which are found in this PUT request, none of the names match the profile at all.  Profile is camel-case with an initial lower-case letter.  The PUT request to update profile seems to use upper-case instead.  So a careful mapping is required.
