### ISSUE TITLE
Redirects Needed

### ISSUE THREAD

**Issue by bstopp** [hlxsites/hsf-commonmoves#156]
1. https://www.commonmoves.com/services/Rentals -> https://www.commonmoves.com/services/rentals
2. https://www.commonmoves.com/services/Commercial -> https://www.commonmoves.com/services/commercial
3. https://www.commonmoves.com/services/Relocation -> https://www.commonmoves.com/services/relocation
4. https://www.commonmoves.com/services/Subdivisions -> https://www.commonmoves.com/services/subdivisions
5. https://www.commonmoves.com/agent-search-results -> https://www.commonmoves.com/search/agent

**Comment by rrusher** [comment]
1 through 5 added.

**Comment by bstopp** [comment]
Completed.
