### ISSUE TITLE
mobile icon cards - sliding cards

### ISSUE THREAD

**Issue by schooolman** [hlxsites/hsf-commonmoves#209]
Currently the mobile icon cards are hidden from view. To match the new designs we need to implement a card sliding system. This can be seen in the avm-report section on the homepage.

**Comment by bstopp** [comment]
Did not realize they changed the icon cards to a carousel view

**Comment by rrusher** [comment]
Is the home screen the only location this change occurs?
<img width="589" alt="Screenshot 2024-05-30 at 11 45 53 AM" src="https://github.com/hlxsites/hsf-commonmoves/assets/6796243/6c537c16-8803-42d9-b6b4-5e9a8ec087f1">
