### ISSUE TITLE
Add Community Listing Block

### ISSUE THREAD

**Issue by bstopp** [hlxsites/hsf-commonmoves#23]
<img width="463" alt="Cursor_and_Local_Communities_We_Serve___Commonwealth_Real_Estate_Berkshire_Hathaway_HomeServices" src="https://user-images.githubusercontent.com/6520270/228311878-e52278a3-8791-4f8a-b054-39c3e5ae418f.png">

**Comment by badvision** [comment]
Already resolved by #118
