### ISSUE TITLE
Contact Us Form

### ISSUE THREAD

**Issue by bstopp** [hlxsites/hsf-commonmoves#81]
Need to figure out where/how this works. Especially the Captcha - if it goes to AEM, we need to find that out quick.

https://www.commonmoves.com/contact-us

This block should also either export a library, or there should be a shared library to display the form and the submission logic so that it can be attached to any link on a page. 

For example, clicking this will open the pre-filled form. Same form as the contact-us page.

<img width="544" alt="Contact Us" src="https://github.com/hlxsites/hsf-commonmoves/assets/6520270/bb59d3c4-5ad7-4c57-aefb-f90d210df640">

**Comment by rrusher** [comment]
The contact us page (office-contact) and contact us sidebar (property-contact) appear to be different forms.
They do submit to the same websiteTopicServlet, see attached.

**Headers**
<img width="1505" alt="Screenshot 2023-11-02 at 2 15 42 PM" src="https://github.com/hlxsites/hsf-commonmoves/assets/6796243/6a34658d-92b7-414a-b6f4-7b1b8b0cd74f">

**Office Contact**
<img width="818" alt="Screenshot 2023-11-02 at 2 20 19 PM" src="https://github.com/hlxsites/hsf-commonmoves/assets/6796243/48107e45-e671-4ac2-b0d1-1547c20f739b">

**Property Contact**
<img width="1198" alt="Screenshot 2023-11-02 at 2 20 58 PM" src="https://github.com/hlxsites/hsf-commonmoves/assets/6796243/e1691483-7927-4f22-ae09-47df8830118f">
