### ISSUE TITLE
Social Feed Block

### ISSUE THREAD

**Issue by bstopp** [hlxsites/hsf-commonmoves#9]
<img width="632" alt="social_feed" src="https://user-images.githubusercontent.com/6520270/224403146-8aefd4f2-f019-4f02-9b84-8ce27dc3ae25.png">

**Comment by irenelagno** [comment]
- need to be loaded as a post process to avoid page load blocking

**Comment by bstopp** [comment]
This should be a drop-in of the library. The JS/CSS needs to beloaded lazy/via worker, and make sure the block's box is a fixed height to start. That will ensure that the PSi is good.

**Comment by bstopp** [comment]
We have an open discussion with the customer on this feature. Adding the block to the page has a dramatic impact on the PSI score.  [See the score here](https://pagespeed.web.dev/analysis/https-feat-juicer-block--hsf-commonmoves--hlxsites-hlx-page-drafts-juicer/mi4qe1dg7f?form_factor=mobile).

We've taken all possible steps to mitigate, but adding to the page will still likely have a detrimental impact on the home page's CWV score.
